import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import { useQuery } from 'react-query';
// import styles from '../styles/Home.module.css';

export default function Home() {
  const { isLoading, error, data: userData } = useQuery('userData', () =>
    fetch('https://jsonplaceholder.typicode.com/users').then(res =>
      res.json()
    )
  )

  if (isLoading) {
    return <h1>Loading...</h1>
  }

  if (error) {
    return <p>{error.message}</p>
  }
  // console.log(data);
  return (
    <div >
      <Head>
        <title>React Query App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <div>
            {
              userData.map((user) => {
                console.log(user.name);
                <div key={user.id}>
                  <h1>{user.name}</h1>
                </div>
              })
            }
          </div>
        </section>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
